#!/usr/bin/env python3
import os
import re

def check_docstrings(dir_path):
    missing_docs = []
    
    for subdir, _, files in os.walk(dir_path):
        for f in files:
            if not f.endswith('.hpp') or f == 'sdl_deleters.hpp':
                continue
            filepath = os.path.join(subdir, f)
            with open(filepath, 'r') as file:
                lines = file.readlines()
                
            for i, line in enumerate(lines):
                if 'auto-generated' in line.lower() or 'generated by' in line.lower():
                    break
                
                # We skip checking docstrings for constructors/destructors that are default or deleted
                # Actually, let's check class/struct and public functions
                code_only = line.split('//')[0]
                
                # Check for class/struct
                class_match = re.search(r'\b(?:class|struct)\s+([A-Za-z0-9_]+)\b', code_only)
                func_match = re.search(r'^\s*(?:[\w<>:]+(?:[*&\s]+)+)+([A-Za-z0-9_]+)\s*\(', code_only)
                
                if class_match or func_match:
                    name = class_match.group(1) if class_match else func_match.group(1)
                    if name in ['if', 'while', 'for', 'switch', 'return', 'catch', 'final']:
                        continue
                    
                    # Look at the previous line for `///`
                    has_doc = False
                    if i > 0 and '///' in lines[i-1]:
                        has_doc = True
                    
                    # Also look at previous non-empty lines if we want to be robust
                    # but typically doxygen is right above
                    j = i - 1
                    while j >= 0:
                        line_j = lines[j].strip()
                        if line_j == '' or line_j.startswith('template'):
                            j -= 1
                        else:
                            break
                            
                    if j >= 0 and ('///' in lines[j] or '/**' in lines[j] or '*' in lines[j]):
                        has_doc = True
                        
                    if not has_doc:
                        missing_docs.append(f"{filepath}:{i+1} - Missing docstring for '{name}'")
                        
    for md in missing_docs:
        print(md)
    if not missing_docs:
        print("All public APIs have docstrings!")

check_docstrings("include/lili2d")
