#!/usr/bin/env python3
import os
import re
import sys

def check_file(filepath):
    errors = []

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except Exception as e:
        return [(0, f"Could not read file: {e}")]

    if any("auto-generated" in line.lower() or "generated by" in line.lower() for line in lines[:5]):
        return []

    is_hpp = filepath.endswith('.hpp')

    in_class = False
    class_name = ""
    private_seen = False
    has_destructor = False
    has_copy_ctor = False
    has_copy_assign = False
    has_move_ctor = False
    has_move_assign = False

    namespaces_found = set()
    namespace_closings = {}

    for i, line in enumerate(lines):
        line_num = i + 1
        line_no_nl = line.rstrip('\n')

        if len(line_no_nl) > 80:
            errors.append((line_num, "Line exceeds 80 characters"))

        if line_no_nl != "" and line_no_nl.strip() == "":
            errors.append((line_num, "Blank line is not completely empty (contains spaces/tabs)"))
        elif line_no_nl != line_no_nl.rstrip(' \t'):
            errors.append((line_num, "Trailing whitespace detected"))

        if line.strip() != "" and re.match(r'^\t* +', line):
            errors.append((line_num, "Indentation uses spaces instead of tabs"))

        code_only = line
        if '//' in code_only:
            code_only = code_only.split('//')[0]
        if '/*' in code_only and '*/' in code_only:
            code_only = re.sub(r'/\*.*?\*/', '', code_only)

        class_match = re.search(r'\b(?:class|struct)\s+([A-Za-z0-9_]+)\b', code_only)
        if class_match:
            name = class_match.group(1)
            if name != "final" and not re.match(r'^[A-Z][a-zA-Z0-9]*$', name):
                errors.append((line_num, f"Class/Struct '{name}' is not PascalCase"))

            in_class = True
            class_name = name
            private_seen = False
            has_destructor = False
            has_copy_ctor = False
            has_copy_assign = False
            has_move_ctor = False
            has_move_assign = False

        if in_class:
            if "public:" in code_only:
                if private_seen:
                    errors.append((line_num, "Class structure: 'public' section must appear before 'private' section"))
            if "private:" in code_only:
                private_seen = True

            if class_name:
                if re.search(rf'~{class_name}\s*\(', code_only): has_destructor = True
                if re.search(rf'{class_name}\s*\(\s*const\s+{class_name}\s*&', code_only): has_copy_ctor = True
                if re.search(rf'operator=\s*\(\s*const\s+{class_name}\s*&', code_only): has_copy_assign = True
                if re.search(rf'{class_name}\s*\(\s*{class_name}\s*&&', code_only): has_move_ctor = True
                if re.search(rf'operator=\s*\(\s*{class_name}\s*&&', code_only): has_move_assign = True

            if re.search(r'^\s*};', code_only):
                in_class = False
                if has_destructor:
                    if not (has_copy_ctor and has_copy_assign and has_move_ctor and has_move_assign):
                        errors.append((line_num, f"Class '{class_name}' violates Rule of 5 (has destructor but missing copy/move constructors or assignment operators)"))

        func_match = re.search(r'^\s*(?:[\w<>:]+(?:[*&\s]+)+)+([A-Za-z0-9_]+)\s*\(', code_only)
        if func_match and not class_match:
            name = func_match.group(1)
            if name not in ['main', 'if', 'while', 'for', 'switch', 'return', 'catch'] and "operator" not in name:
                if in_class and name == class_name:
                    pass
                elif in_class and name == f"~{class_name}":
                    pass
                elif name[0].isupper():
                    pass # Ignore PascalCase (likely constructors or type instantiations)
                elif not re.match(r'^[a-z][a-zA-Z0-9]*$', name):
                    errors.append((line_num, f"Function '{name}' is not camelCase"))

        const_match = re.search(r'\bconst\s+[\w<>:]+\s+([A-Za-z0-9_]+)\b\s*=', code_only)
        if const_match:
            name = const_match.group(1)
            if not re.match(r'^[A-Z0-9_]+$', name):
                errors.append((line_num, f"Constant '{name}' is not UPPER_CASE"))

        var_match = re.search(r'^\s*(?!using\b)([A-Za-z0-9_<>:]+)\s+([A-Za-z0-9_]+)\s*=', code_only)
        if var_match and not const_match:
            type_str = var_match.group(1)
            name = var_match.group(2)
            if type_str not in ['if', 'else', 'while', 'for', 'return'] and not re.match(r'^[a-z0-9_]+$', name):
                errors.append((line_num, f"Variable '{name}' is not snake_case"))

        if is_hpp and not in_class:
            if '{' in code_only and not class_match and "namespace" not in code_only and "enum" not in code_only:
                errors.append((line_num, "Header logic check: found '{' outside of a class/struct/namespace (headers should only have declarations)"))

        ns_match = re.search(r'^\s*namespace\s+([A-Za-z0-9_]+)\b', code_only)
        if ns_match:
            namespaces_found.add(ns_match.group(1))

        closing_match = re.search(r'\}\s*//\s*namespace\s+([A-Za-z0-9_]+)\b', line)
        if closing_match:
            ns_name = closing_match.group(1)
            if f"}}  // namespace {ns_name}" not in line:
                errors.append((line_num, f"Namespace closing bracket must have exactly 2 spaces before the comment: '}}  // namespace {ns_name}'"))
            namespace_closings[ns_name] = line_num

    for ns in namespaces_found:
        if ns not in namespace_closings:
            errors.append((len(lines), f"Namespace '{ns}' is missing its commented closing bracket: '}}  // namespace {ns}'"))

    return errors

def main():
    root_dir = "."
    if len(sys.argv) > 1:
        root_dir = sys.argv[1]

    all_errors = {}

    print(f"Scanning for C++ coding norms in '{os.path.abspath(root_dir)}'...")

    files_checked = 0
    for subdir, _, files in os.walk(root_dir):
        if any(skip in subdir for skip in ['.git', 'build', 'cmake-build', 'node_modules', 'vendor']):
            continue

        for f in files:
            if f.endswith('.cpp') or f.endswith('.hpp') or f.endswith('.h') or f.endswith('.c'):
                filepath = os.path.join(subdir, f)
                files_checked += 1
                errors = check_file(filepath)
                if errors:
                    rel_path = os.path.relpath(filepath, root_dir)
                    all_errors[rel_path] = errors

    if files_checked == 0:
        print("No .cpp or .hpp files found to check.")
        sys.exit(0)

    if not all_errors:
        print(f":3 Success! All {files_checked} files respect the coding norms.")
        sys.exit(0)
    else:
        print(":O Coding norm violations found:\n")
        for filepath, errors in all_errors.items():
            for line_num, msg in errors:
                print(f"{filepath}:{line_num} - {msg}")

        print(f"\nFound errors in {len(all_errors)} out of {files_checked} files.")
        sys.exit(1)

if __name__ == "__main__":
    main()
